name: Publish
on:
  push:
    tags:
      - v*

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mkdocs-custom-tags-attributes
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install pipenv
        run: pip install pipenv
      - name: Build
        run: |
          pipenv install
          pipenv run dist
      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
